export const redisKeys = {
  AREAS: 'KEY_AREAS',
  CARGOS: 'KEY_CARGOS',
  CONTRATAS: 'KEY_CONTRATAS',
  VISTAS: 'KEY_VISTAS',
  ZONAS: 'KEY_ZONAS',
  
  GESTORES: 'KEY_EMPLEADO_GESTORES',
  AUDITORES: 'KEY_EMPLEADO_AUDITORES',

  RUTAS_TOA: 'KEY_RUTAS_TOA',
  LIMA_AVERIAS: 'KEY_LIMA_AVERIAS',
  LIMA_ALTAS: 'KEY_LIMA_ALTAS',
  PROVINCIA_AVERIAS: 'KEY_PROVINCIA_AVERIAS',
  PROVINCIA_ALTAS: 'KEY_PROVINCIA_ALTAS'
}